export enum ErrorCode {
  ERROR_TASK_IN_PROGRESS = 'ERROR_TASK_IN_PROGRESS',
  ERROR_USER_DATA_IMPORT = 'ERROR_USER_DATA_IMPORT',
  ERROR_USER_PHONE_ALREADY_EXISTS = 'ERROR_USER_PHONE_ALREADY_EXISTS',
}

export enum ImportExcelRowErrorCode {
  EMPTY_FULLNAME = 'EMPTY_FULLNAME',
  EMPTY_PHONE_NUMBER = 'EMPTY_PHONE_NUMBER',
  LESS_THAN_2_CHARACTERS = 'LESS_THAN_2_CHARACTERS',
  INVALID_CHARACTERS_IN_NAME = 'INVALID_CHARACTERS_IN_NAME',
  INVALID_PHONE_NUMBER = 'INVALID_PHONE_NUMBER',
  PHONE_NUMBER_ALREADY_EXIST = 'PHONE_NUMBER_ALREADY_EXIST',
  PHONE_NUMBER_DUPLICATED_IN_SHEET = 'PHONE_NUMBER_DUPLICATED_IN_SHEET',
}

export const ErrorMessage = {
  UNKNOWN_ERROR: 'Có lỗi xảy ra',
  SEND_FLAG_ERROR: 'Lỗi khi gửi flag',
  SEND_TIME_ERROR: 'Lỗi khi gửi thời gian',
  CANNOT_COMPLETE_ERROR: 'Không thể kết thúc',
}
