name: ai-ic-fe-test

services:
  ai_ic_fe:
    container_name: ic_fe_test
    build:
      context: .
      dockerfile: Dockerfile
    image: ai-ic-fe
    ports:
      - 5174:80
    restart: always
    environment:
      - BACKEND_URL=${BACKEND_URL:-http://api:8000}
    networks:
      - default
      - traefik_net

networks:
  traefik_net:
    external: true
