sonar.projectKey=rtalk-admin-be
sonar.projectName=Rtalk Admin BE
sonar.host.url=http://10.2.21.138:9124
sonar.login=${SONAR_TOKEN}
sonar.sources=.
sonar.exclusions=**/node_modules/**,**/*.test.ts,**/*.spec.ts
sonar.javascript.lcov.reportPaths=coverage/lcov.info
