
name: run CI

on:
  pull_request:
    branches:
      - '**'
      - staging
      - develop

jobs:
  check-flake8:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry

      - name: Install dependencies via Poetry
        run: |
          poetry install --no-root
          poetry install --no-root --with test

      - name: Lint with flake8
        run: |
          poetry run flake8 app/ --count --select=E9,F63,F7,F82 --show-source --statistics
          poetry run flake8 app/ --count --exit-zero --max-complexity=10 --max-line-length=120 --statistics

  run-unit-test:
    runs-on: ubuntu-latest
    needs: check-flake8
    continue-on-error: ${{ github.ref == 'refs/heads/preprod' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry

      - name: Cache .venv based on lockfile
        uses: actions/cache@v4
        with:
          path: .venv
          key: venv-${{ runner.os }}-py3.10-${{ hashFiles('poetry.lock') }}
          restore-keys: |
            venv-${{ runner.os }}-py3.10-

      - name: Install dependencies via Poetry
        run: |
          poetry install --no-root
          poetry install --no-root --with test

      - name: Run tests (pytest + coverage)
        env:
          POSTGRES_SERVER: ""
          POSTGRES_USER: ""
          POSTGRES_PASSWORD: ""
          POSTGRES_DB: ""
          POSTGRES_PORT: ""
          JWT_SECRET_KEY: ""
          MINIO_PUBLIC_ENDPOINT: ""
          ALLOW_ORIGINS: ""
          MINIO_ENDPOINT: ""
          MINIO_ACCESS_KEY: ""
          MINIO_SECRET_KEY: ""
          MINIO_BUCKET_NAME: ""
          MINIO_SECURE: true
          MINIO_PUBLIC_SECURE: true
        run: |
          mkdir -p reports
          poetry run pytest -q \
            --maxfail=1 --disable-warnings \
            --cov=app \
            --cov-report=xml \
            --cov-report=term-missing \
            --junitxml=reports/junit.xml

#      - name: Upload artifacts (coverage.xml & JUnit)
#        if: always()
#        uses: actions/upload-artifact@v4
#        with:
#          name: pytest-artifacts
#          path: |
#            coverage.xml
#            reports/junit.xml


  build-docker-image:
    runs-on: ubuntu-latest
    needs: run-unit-test
    if: always() && github.ref != 'refs/heads/preprod'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          push: false
          cache-from: type=gha
          cache-to: type=gha,mode=max